//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios de este archivo pueden provocar un comportamiento inesperado y se perderán si
//     el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IU.Modulos.Contabilidad
{


    public partial class CentrosCostosProrrateosAgregar
    {
        /// <summary>
        /// AgregarDatos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IU.Modulos.Contabilidad.Controles.CentrosCostosProrrateosDatos AgregarDatos;
    }
}
