//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios de este archivo pueden provocar un comportamiento inesperado y se perderán si
//     el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IU.Modulos.Medicina
{


    public partial class PrestacionesConsultar
    {
        /// <summary>
        /// Control ModificarDatos.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::IU.Modulos.Medicina.Controles.PrestacionesModificarDatos ctrModificarDatos;
    }
}
